// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: panmon_agent.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseStatsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpu  *float64 `protobuf:"fixed64,1,opt,name=cpu,proto3,oneof" json:"cpu,omitempty"`
	Mem  *float64 `protobuf:"fixed64,2,opt,name=mem,proto3,oneof" json:"mem,omitempty"`
	Disk *float64 `protobuf:"fixed64,3,opt,name=disk,proto3,oneof" json:"disk,omitempty"`
}

func (x *BaseStatsReply) Reset() {
	*x = BaseStatsReply{}
	mi := &file_panmon_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseStatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseStatsReply) ProtoMessage() {}

func (x *BaseStatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_panmon_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseStatsReply.ProtoReflect.Descriptor instead.
func (*BaseStatsReply) Descriptor() ([]byte, []int) {
	return file_panmon_agent_proto_rawDescGZIP(), []int{0}
}

func (x *BaseStatsReply) GetCpu() float64 {
	if x != nil && x.Cpu != nil {
		return *x.Cpu
	}
	return 0
}

func (x *BaseStatsReply) GetMem() float64 {
	if x != nil && x.Mem != nil {
		return *x.Mem
	}
	return 0
}

func (x *BaseStatsReply) GetDisk() float64 {
	if x != nil && x.Disk != nil {
		return *x.Disk
	}
	return 0
}

var File_panmon_agent_proto protoreflect.FileDescriptor

var file_panmon_agent_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x61, 0x6e, 0x6d, 0x6f, 0x6e, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x70, 0x0a, 0x0e, 0x42, 0x61, 0x73, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x15, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x03, 0x63, 0x70, 0x75, 0x88, 0x01, 0x01, 0x12,
	0x15, 0x0a, 0x03, 0x6d, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x48, 0x01, 0x52, 0x03,
	0x6d, 0x65, 0x6d, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x64, 0x69, 0x73, 0x6b, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x01, 0x48, 0x02, 0x52, 0x04, 0x64, 0x69, 0x73, 0x6b, 0x88, 0x01, 0x01, 0x42,
	0x06, 0x0a, 0x04, 0x5f, 0x63, 0x70, 0x75, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6d, 0x65, 0x6d, 0x42,
	0x07, 0x0a, 0x05, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x32, 0x48, 0x0a, 0x08, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x53, 0x76, 0x63, 0x12, 0x3c, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x61, 0x73, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_panmon_agent_proto_rawDescOnce sync.Once
	file_panmon_agent_proto_rawDescData = file_panmon_agent_proto_rawDesc
)

func file_panmon_agent_proto_rawDescGZIP() []byte {
	file_panmon_agent_proto_rawDescOnce.Do(func() {
		file_panmon_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_panmon_agent_proto_rawDescData)
	})
	return file_panmon_agent_proto_rawDescData
}

var file_panmon_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_panmon_agent_proto_goTypes = []any{
	(*BaseStatsReply)(nil), // 0: api.BaseStatsReply
	(*emptypb.Empty)(nil),  // 1: google.protobuf.Empty
}
var file_panmon_agent_proto_depIdxs = []int32{
	1, // 0: api.AgentSvc.SendBaseStats:input_type -> google.protobuf.Empty
	0, // 1: api.AgentSvc.SendBaseStats:output_type -> api.BaseStatsReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_panmon_agent_proto_init() }
func file_panmon_agent_proto_init() {
	if File_panmon_agent_proto != nil {
		return
	}
	file_panmon_agent_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_panmon_agent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_panmon_agent_proto_goTypes,
		DependencyIndexes: file_panmon_agent_proto_depIdxs,
		MessageInfos:      file_panmon_agent_proto_msgTypes,
	}.Build()
	File_panmon_agent_proto = out.File
	file_panmon_agent_proto_rawDesc = nil
	file_panmon_agent_proto_goTypes = nil
	file_panmon_agent_proto_depIdxs = nil
}
